# Generated by Django 4.2.4 on 2023-08-16 02:29

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='recurring',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='home_phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Home phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=phone_field.models.PhoneField(blank=True, help_text='Mobile number', max_length=31),
        ),
    ]
